server:
  port: 8090

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soom
    username: root
    password:

    # Hikari connection pool configuration
    hikari:
      minimum-idle: 3  # Minimum number of idle connections
      maximum-pool-size: 5  # The maximum number of connections in the connection pool, the default is 10
      max-lifetime: 1800000  # This attribute controls the longest life cycle of the connection in the pool, the value 0 means infinite life cycle, the default is 1800000, which is 30 minutes
      connection-test-query: SELECT 1

    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        jdbc:
          batch_size: 30
    open-in-view: false